# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c51bf1ee1df45934b03e8797562e0d18e9f709a35ab0f6d43938fc5cb21adf52a8b117d68c7d6326a4b8c9afa6d83da44a2b958c507d0484fb981ee38dc83908

test:
  secret_key_base: a108fe1e699abaccd0be0d188dc00b748b8dbcae92bc3225debaff6b5c2c1a46377489639164023191309eacc51425e55e2d1c0ed9908f7ee5ed4e3ec4c2e5f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
